title: Chelwin's Home
logo: /assets/img/logo.png
author: Chelwin
email: my-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my little corner on the interwebs. Have fun!
show_downloads: true
google_analytics:
# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
